[tool.ruff]
target-version = "py311"
line-length = 100
fix = true
show-fixes = true
lint.select = ["E", "F", "I", "UP", "B", "SIM", "N"]
lint.ignore = ["E501"]
exclude = [".git", ".mypy_cache", ".ruff_cache", "venv", "build", "dist"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true
pretty = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["scripts.*"]
disallow_untyped_calls = true
