name: Daily Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python scripts/feed.py
        env:
          CSE_ID: ${{ secrets.CSE_ID }}
          CSE_KEY: ${{ secrets.CSE_KEY }}
          COMPANY_CONFIG: ${{ github.workspace }}/config/companies.json
          SETTINGS_CONFIG: ${{ github.workspace }}/config/settings.json
          JSON_SALT: ${{ secrets.JSON_SALT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat data/manifest.json
      - name: Print json_path from manifest
        run: |
          python scripts/print_json_path.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html data/
          git commit -m "chore: update daily feed [skip ci]" || echo "No changes"
          git push

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
