name: Build and Deploy Feed

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Generate feed (HTML + JSON)
        env:
          CSE_ID: ${{ secrets.CSE_ID }}
          CSE_KEY: ${{ secrets.CSE_KEY }}
          COMPANY_CONFIG: ${{ github.workspace }}/config/companies.json
          SETTINGS_CONFIG: ${{ github.workspace }}/config/settings.json
          JSON_SALT: ${{ secrets.JSON_SALT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m scripts.feed
          touch .nojekyll
          echo "== site tree ==" && tree -a -L 2 || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
