name: Build and Deploy Feed

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run feed.py
        env:
          CSE_ID: ${{ secrets.CSE_ID }}
          CSE_KEY: ${{ secrets.CSE_KEY }}
          COMPANY_CONFIG: ${{ github.workspace }}/config/companies.json
          SETTINGS_CONFIG: ${{ github.workspace }}/config/settings.json
          JSON_SALT: ${{ secrets.JSON_SALT }}
        run: python -m scripts.feed

      - name: Show manifest
        run: cat data/manifest.json

      - name: Print json path
        run: python -m scripts.print_json_path

      - name: Commit and push feed artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html data/
          git commit -m "chore: update daily feed [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
