name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run feed.py
        env:
          CSE_ID: ${{ secrets.CSE_ID }}
          CSE_KEY: ${{ secrets.CSE_KEY }}
          COMPANY_CONFIG: ${{ github.workspace }}/config/companies.json
          SETTINGS_CONFIG: ${{ github.workspace }}/config/settings.json
          JSON_SALT: ${{ secrets.JSON_SALT }}
        run: |
          python scripts/feed.py

      - name: Verify outputs
        run: |
          test -f index.html || (echo "index.html missing!" && exit 1)
          test -f data/manifest.json || (echo "manifest.json missing!" && exit 1)
          echo "Outputs verified: index.html + manifest.json"

      - name: Show manifest & JSON path
        run: |
          cat data/manifest.json
          python - <<'PY'
import json, pathlib
mf = pathlib.Path("data/manifest.json")
data = json.loads(mf.read_text())
print("Latest JSON path:", data.get("json_path"))
p = pathlib.Path(data.get("json_path"))
if not p.exists():
    raise SystemExit(f"JSON file {p} does not exist!")
print("JSON file exists, count:", data.get("count"))
PY
